replicaCount: 1

namespace:
  create: true
  name: debit-card-api

image:
  repository: debit-card-api
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: true
  className: nginx
  host: debit-card-api.local

stip:
  enabled: false

tls:
  createSelfSigned: true
  secretName: debit-card-api-tls
  commonName: debit-card-api.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
