apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debit-card-api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "debit-card-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "debit-card-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "debit-card-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: debit-card-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STIP_Enabled
              value: {{ .Values.stip.enabled | quote }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: /https
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
