{{- if .Values.tls.createSelfSigned }}
{{- $ca := genCA (printf "%s-ca" (include "debit-card-api.fullname" .)) 365 -}}
{{- $cert := genSignedCert .Values.tls.commonName nil nil 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "debit-card-api.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
